version: '3'

networks:
  wordpress:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: __APPNAME_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/html:delegated
    depends_on:
      - php
      - mysql
      - phpmyadmin
    networks:
      - wordpress

  mysql:
    image: mysql:5.7.29
    container_name: __APPNAME_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: _APPNAME
      MYSQL_USER: __USER
      MYSQL_PASSWORD: __PASS
      MYSQL_ROOT_PASSWORD: __PASS
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wordpress

  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - mysql
    container_name: __APPNAME_phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    networks:
      - wordpress

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: __APPNAME_php
    volumes:
      - ./app:/var/www/html:delegated
    networks:
      - wordpress

  wp:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: __APPNAME_wp
    entrypoint: ['wp', '--allow-root']
    volumes:
      - ./app:/var/www/html:delegated
    networks:
      - wordpress
